### ISSUE TITLE
作者您好，既然是无监督的话，为什么需要Annotations

### ISSUE THREAD

**Issue by Fairy1213** [cpystan/PSM#1]
Annotations里面应该放什么样子的标签

**Comment by cpystan** [comment]
无监督指的是不需要手工标签，我们的伪标签是通过自监督学习产生的。

**Comment by cpystan** [comment]
> Annotations里面应该放什么样子的标签

无监督指的是不需要手工标签，我们的伪标签是通过自监督学习产生的。

**Comment by Fairy1213** [comment]
但是您在设置数据集的时候就用到了annotions，并且在自监督学习里也调用了标签，我想知道自监督学习的时候数据集annotations里面是空的还是您提供了其他伪标签

**Comment by cpystan** [comment]
> 但是您在设置数据集的时候就用到了annotions，并且在自监督学习里也调用了标签，我想知道自监督学习的时候数据集annotations里面是空的还是您提供了其他伪标签

训练的时候没有用annotation， 只在测试的时候计算指标用。

**Comment by Fairy1213** [comment]
所以最开始annotations可以是空的吗，然后通过自监督学习，会自动生成annotations吗

**Comment by cpystan** [comment]
> 所以最开始annotations可以是空的吗，然后通过自监督学习，会自动生成annotations吗

从原理上来说是可以的。
