### ISSUE TITLE
MoNuseg数据集求分享

### ISSUE THREAD

**Issue by asdddsdf** [cpystan/PSM#2]

**Comment by cpystan** [comment]
Just arrange your MoNuSeg as following:
MonuSeg
-Train
--Annotations
--Tissue_Images
-Test
--xxxxx.xml
--xxxxx.xml

**Comment by asdddsdf** [comment]
您好：
&nbsp; &nbsp; &nbsp; 我下载了MoNuSeg 2018 Training Data压缩包，将其解压以后把xx.tif改为xx.png。数据集路径：/home/work/PSM_data
PSM_data/MoNuSeg 2018 Training Data
--Annotations
&nbsp; &nbsp;TCGA-18-5592-01Z-00-DX1.xml
&nbsp; &nbsp;...
--Tissue_Images
&nbsp; &nbsp;TCGA-18-5592-01Z-00-DX1.png
&nbsp; &nbsp;...
PSM_data/MoNuSegTestData
TCGA-2Z-A9J9-01A-01-TS1.png
TCGA-2Z-A9J9-01A-01-TS1.xml


&nbsp; &nbsp; &nbsp; &nbsp;我在options.py中修改了Data specifications的train和test的参数路径,但是运行中总是报出这样的错误：
(conda_1) aistudio@:~/work/PSM/PSM-master$ python main_monuseg.py --mode 'train_random_rotate'    #Predicting rotate --EPOCH : 0  Traceback (most recent call last):   File "main_monuseg.py", line 580, in <module&gt;     trainer_selfsupervised_random_rotate(EPOCH,args,model, loss_func, optimizer)   File "main_monuseg.py", line 192, in trainer_selfsupervised_random_rotate     loader = data.get_monuseg(epoch, args)   File "/home/aistudio/work/PSM/PSM-master/data.py", line 114, in get_monuseg     o = Data(args, input_train, label_train, input_val, label_val ,input_test,label_test)   File "/home/aistudio/work/PSM/PSM-master/data.py", line 51, in __init__     self.test_loader = data.DataLoader(   File "/home/aistudio/work/anaconda3/envs/conda_1/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 270, in __init__     sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]   File "/home/aistudio/work/anaconda3/envs/conda_1/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 102, in __init__     raise ValueError("num_samples should be a positive integer " ValueError: num_samples should be a positive integer value, but got num_samples=0
报错显示加载的数据大小为0，不知道问题出在了哪，请问应该怎么弄呢?🤔




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cpystan/PSM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月27日(星期三) 下午2:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cpystan/PSM] MoNuseg数据集求分享，网上的无法加载到代码中 (Issue #2)





 
Just arrange your MoNuSeg as following:
 MonuSeg
 -Train
 --Annotations
 --Tissue_Images
 -Test
 --xxxxx.xml
 --xxxxx.xml

**Comment by cpystan** [comment]
您好，这个报错似乎是因为测试集并没有加载成功。可以关注下get_monuseg这个函数中的input_test,和input_label是否为空。

**Comment by asdddsdf** [comment]
您好：
&nbsp; &nbsp; &nbsp; 感谢您的回复，然而问题还没解决🤔。在data.py中我看了下.tif图片可以加载，但是打印输出lable数量为0，似乎是格式不对无法加载。因为81行代码:label_test = sorted([item for item in test_list if item.endswith('_binary.png')]) 去加载以'_binary.png'结尾的lable,然而下载的MoNuSegTestData数据集中只有.tif与.xml两个格式的文件。应该怎么办呢？


PS:报错如图:







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cpystan/PSM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月11日(星期三) 中午1:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cpystan/PSM] MoNuseg数据集求分享，网上的无法加载到代码中 (Issue #2)





 
您好，这个报错似乎是因为测试集并没有加载成功。可以关注下get_monuseg这个函数中的input_test,和input_label是否为空。

**Comment by cpystan** [comment]
.xml文件以json格式保存了细胞的label。需要先预处理一下，把它转化成二值图。

**Comment by asdddsdf** [comment]
您好：
&nbsp; &nbsp; &nbsp; 按照您说的已经将train和test里的.xml文件转化为了.png格式。数据集目录：
PSM_data
-MoNuSeg 2018 Training Data
--Annotations
&nbsp; -TCGA-18-5592-01Z-00-DX1_binary.png
&nbsp; -TCGA-18-5592-01Z-00-DX1.xml
&nbsp; ...
--Tissue Images
&nbsp; -TCGA-18-5592-01Z-00-DX1.tif
&nbsp; &nbsp;...
--MoNuSegTestData&nbsp;&nbsp;
&nbsp; &nbsp;TCGA-2Z-A9J9-01A-01-TS1_binary.png
&nbsp; &nbsp;TCGA-2Z-A9J9-01A-01-TS1。tif
&nbsp; &nbsp;...


运行中出现错误如图：


data.py的第19行，label = self.label[item]。这里，item可能是一个超出self.label列表范围的索引。这个索引的错误如何去调试，请详细说明应该修改哪部分代码。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cpystan/PSM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月12日(星期四) 中午1:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cpystan/PSM] MoNuseg数据集求分享，网上的无法加载到代码中 (Issue #2)





 
.xml文件以json格式保存了细胞的label。需要先预处理一下，把它转化成二值图。

**Comment by cpystan** [comment]
我这里看不到你发的截图

**Comment by asdddsdf** [comment]
您好：
&nbsp; &nbsp; &nbsp; 运行报错如下：


(conda_1) ***@***.***:~/work/PSM/PSM-master$ python main_monuseg.py --mode 'train_base'&nbsp; &nbsp; #Similarity Measure
--EPOCH : 0&nbsp;
[]
Traceback (most recent call last):
&nbsp; File "main_monuseg.py", line 566, in <module&gt;
&nbsp; &nbsp; trainer_selfsupervised(EPOCH,args,model, loss_func, optimizer)
&nbsp; File "main_monuseg.py", line 132, in trainer_selfsupervised
&nbsp; &nbsp; loader = data.get_monuseg(epoch, args)
&nbsp; File "/home/aistudio/work/PSM/PSM-master/data.py", line 114, in get_monuseg
&nbsp; &nbsp; o = Data(args, input_train, label_train, input_val, label_val ,input_test,label_test)
&nbsp; File "/home/aistudio/work/PSM/PSM-master/data.py", line 51, in __init__
&nbsp; &nbsp; self.test_loader = data.DataLoader(
&nbsp; File "/home/aistudio/work/anaconda3/envs/conda_1/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 270, in __init__
&nbsp; &nbsp; sampler = RandomSampler(dataset, generator=generator)&nbsp; # type: ignore[arg-type]
&nbsp; File "/home/aistudio/work/anaconda3/envs/conda_1/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 102, in __init__
&nbsp; &nbsp; raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cpystan/PSM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月13日(星期五) 下午2:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cpystan/PSM] MoNuseg数据集求分享，网上的无法加载到代码中 (Issue #2)





 
我这里看不到你发的截图

**Comment by cpystan** [comment]
有较多人反应data读取问题，我们将review一下代码，并把修正版版本及时发布。

**Comment by cpystan** [comment]
代码已更新

**Comment by asdddsdf** [comment]
您好：
&nbsp; &nbsp; &nbsp; 根据修改后的代码，更改了参数的数据集路径，数据集结构：
-MoNuSeg 2018 Training Data
--Annotations
&nbsp; -TCGA-18-5592-01Z-00-DX1_binary.png
&nbsp; ...
--Tissue Images
&nbsp; -TCGA-18-5592-01Z-00-DX1.tif
&nbsp; &nbsp;...
--MoNuSegTestData&nbsp;
&nbsp; &nbsp;TCGA-2Z-A9J9-01A-01-TS1.tif
&nbsp; &nbsp;...
依然无法复现，总是报错:
(PSM) ***@***.***:~/work/PSM-master$ python main_monuseg.py --mode 'train_base'&nbsp; &nbsp; #Similarity Measure
--EPOCH : 0&nbsp;
Traceback (most recent call last):
&nbsp; File "main_monuseg.py", line 676, in <module&gt;
&nbsp; &nbsp; trainer_selfsupervised(EPOCH,args,model, loss_func, optimizer)
&nbsp; File "main_monuseg.py", line 134, in trainer_selfsupervised
&nbsp; &nbsp; loader = data.get_monuseg(epoch, args)
&nbsp; File "/home/aistudio/work/PSM-master/data.py", line 114, in get_monuseg
&nbsp; &nbsp; o = Data(args, input_train, label_train, input_val, label_val ,input_test,label_test)
&nbsp; File "/home/aistudio/work/PSM-master/data.py", line 39, in __init__
&nbsp; &nbsp; drop_last=True
&nbsp; File "/home/aistudio/work/anaconda3/envs/conda_1/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 270, in __init__
&nbsp; &nbsp; sampler = RandomSampler(dataset, generator=generator)&nbsp; # type: ignore[arg-type]
&nbsp; File "/home/aistudio/work/anaconda3/envs/conda_1/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 103, in __init__
&nbsp; &nbsp; "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0
显示数据集中没有样本，即num_samples=0。图片文件没有被正确加载。







------------------ 原始邮件 ------------------
发件人:                                                                                                                        "cpystan/PSM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月11日(星期三) 中午1:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cpystan/PSM] MoNuseg数据集求分享，网上的无法加载到代码中 (Issue #2)





 
您好，这个报错似乎是因为测试集并没有加载成功。可以关注下get_monuseg这个函数中的input_test,和input_label是否为空。
