### ISSUE TITLE
about data arrangement

### ISSUE THREAD

**Issue by cyan135** [cpystan/PSM#4]
作者您好：
     请问在准备数据集时需要按照代码中的这些带有特定后缀的命名方式进行命名吗？如data.py 82行
input_test = sorted([item for item in test_list if item.endswith('tif')])
label_test = sorted([item for item in test_list if item.endswith('_binary.png')])
中的‘_binary.png’。
似乎是必须提供test的label，是仅用于evaluation吗？

**Comment by cyan135** [comment]
以及请问_edge.png的作用是什么呢？代码中没有找到在哪存储过这个后缀类型的数据图片

**Comment by cpystan** [comment]
有较多人反应data读取问题，我们将review一下代码，并把修正版版本及时发布。

**Comment by cpystan** [comment]
代码已更新
